### ISSUE TITLE
Maxent fails in MnO tutorial

### ISSUE THREAD

**Issue by EarlHummocks** [ru-ccmt/eDMFT#4]
Hi!

I am trying the MnO tutorial, but I get the following error when trying to run maxent. Has anyone experienced this?

```
nb= 2 nz= 0
beta= 38.680000000000206
df= -4.121082513703822e-19
beta= 38.680000000000206
normalization= 1.000000000000616
Model normalization= 1.000000000000616
Aw normalization= 1.0000000000006164
0 Restarting maxent with rfac= 1.0 alpha= 1000
Traceback (most recent call last):
  File "/apps/eDMFT/3EDMFTF/bin/maxent_run.py", line 55, in <module>
    (Aw, omega) = MaximumEntropy(params, tau, Gt)
  File "/apps/eDMFT/3EDMFTF/bin/maxentropy.py", line 126, in MaximumEntropy
    me.maxent(Aw,rfac,alpha,temp,Ker,sxt,Gt,model,dom,p['Asteps'],iseed)
OverflowError: Python int too large to convert to C int
```

**Comment by RayAmini** [comment]
It means that an integer value is too large to handle for the parts of the code written in C. Probably it is `p['Asteps']`, or `iseed`.

Please print these numbers by putting
`print(p['Asteps'], iseed)`

before the line

`me.maxent(Aw,rfac,alpha,temp,Ker,sxt,Gt,model,dom,p['Asteps'],iseed)`

in the maxentropy.py file, in order to identify which it is.

**Comment by RayAmini** [comment]
Within the maxent subroutine (maxent_routines.f90), iseed is declared as INTEGER

`INTEGER, intent(in)   :: nt, nw, steps, iseed`

which means that it expects a 32-bit integer.

But iseed=3435014071, which is outside of the range -2^31, ..., 2^31-1 for signed 32-bit integers.

The value is generated in maxentropy.py by any of the python commands:

`iseed = random.randint(0,2**32-1)`
or
` iseed = random.randint(0,maxint)`

 If we set 

`iseed = random.randint(0,2**31-1)`

in all places, we will always get a a number that is within the allowed range.

**Comment by Nagasapa** [comment]
Hii @RayAmini 
did your run_dmft.py worked ? If it worked could you share on how to install it or run it for MnO , because i am facing problems running run_dmft.py code .
Thank you.

**Comment by RayAmini** [comment]
> Hii [@RayAmini](https://github.com/RayAmini) did your run_dmft.py worked ? If it worked could you share on how to install it or run it for MnO , because i am facing problems running run_dmft.py code . Thank you.

Yes, it worked. I believe there are some compiler/system issues that were not foreseen when the code was written. However, issue #11 that you raised is probably down to a version mismatch, not a compilation issue or faulty input files.
